repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-json
    -   id: pretty-format-json
        args: ["--autofix"]
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-case-conflict
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
-   repo: https://github.com/p15r/pre-commit-hooks.git
    rev: v0.1.1
    hooks:
    -   id: markdown-detect-nonref-links
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
-   repo: https://github.com/PyCQA/flake8.git
    rev: 3.8.4
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-no-eval
    -   id: python-no-log-warn
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
        args: [--exclude, tests/]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
    -  id: reorder-python-imports

