name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Install Python dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m pip install -r tests/requirements-dev.txt

      - name: Executing tests
        run: |
          cd $GITHUB_WORKSPACE
          ./run_tests.sh
