name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Install Python dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python3 -m pip install -r tests/requirements-dev.txt

      - name: Executing tests
        run: |
          cd $GITHUB_WORKSPACE
          ./run_tests.sh
